### ISSUE TITLE
Images not rendering in DocViewer

### ISSUE THREAD

**Issue by alexholcombe** [simbrain/simbrain#17]
E.g, if you open autoAssociatorPart1.zip in workspaces/courseMaterials, there are a number of hyperlinks to images that work if you open the DocViewer document outside of Simbrain, but not inside Simbrain.

I tried putting the image file and making a local link in SimBrain.jar's folder, and also in the workspaces folder, but it didn't work. Finally I tried opening the workspace .zip file and putting it in there, but I can't get the workspace to open even if I do the minimum of unzipping it and then rezipping it. Somehow that seems to screw up the workspace file! @jyoshimi

**Comment by alexholcombe** [comment]
It started working!  Maybe it just was taking a very long time to load the images over my slow network connection? In any case, I still would like to know what the default path is so that I can put the images locally rather than have to have internet access working well.

**Comment by jyoshimi** [comment]
Thanks for this Alex.  Yeah I also see the delay.  I'm not sure why.   To show local images see this documentation

http://simbrain.net/Documentation/docs/Pages/DocViewer.html

It's weird syntax.   But hopefully the examples there at the bottom explain how it works.   Everything is by default relative to the Simbrain folder.      There may be a way to use absolute paths but I have not tried it, at least not recently!   You can also pull images from the internet and there as I recall standard html works fine.

Let me know if there are further questions and I'll leave this open for now in case the images _don't_ show up on other systems

Oh the issue of zipping / rezipping is a known issue, though there is no actual github issue opened for that...
