### ISSUE TITLE
Resize of windows when open in a smaller screen than Simbrain window would be nice

### ISSUE THREAD

**Issue by alexholcombe** [simbrain/simbrain#20]
When open network on low-resolution screen, windows do not get smaller and it seems impossible to resize them (because their drag-handles are far offscreen). This is a problem when teaching because most projectors have such low resolution.

Obviously this is a low-priority issue, just would be nice to have.

**Comment by jyoshimi** [comment]
Yes good point.  I have run in to this too.   Any suggestions on a good solution?  I think the easiest, quickest thing, would be a command that just fits every window in the viewable part of the desktop.   That could probably be done fairly quickly.  But I'd be interested in hearing other suggestions.

**Comment by alexholcombe** [comment]
I think that, a command, is defintely good enough!

**Comment by jyoshimi** [comment]
I was going to make one command to just move all open windows to the center, but then I realized that that could mess up some things that are already nicely formatted.  So I think I'll just make a menu with submenus--one for each open window--and then by selecting one of those windows it gets pulled to the center.   Maybe the menu can be "Recenter Window"  with one submenu item for each open window.    Yeah, I think I'll plan on doing that, unless anyone objects or has a better idea.

**Comment by jyoshimi** [comment]
Resolved with 64f3954309d9e8edf1165eb550b406798fb69b23
