### ISSUE TITLE
Text field values are not formatted based on locale

### ISSUE THREAD

**Issue by zachtosi** [simbrain/simbrain#35]
The was brought to light in #34 , and has been fixed for neuron panels in eb71f6cefc959dbcd607f01fa6f7427d7c4fcbd6, however the problem persists pretty much everywhere else there are text fields, as I have discovered a pattern of habitual use of JTextField over JFormattedTextField. Fortunately (or perhaps unfortunately) Simbrain's default check/parse methods DO take Locale into account leading to a feedback cycle where the text fields are filled with values formatted one way (always USA English) but parsed based on the host machine's Locale.

Replication:
1. In SynapseDialog.java add the following static initializer block:
   
   static{
      Locale.setDefaultLocale(Locale.GERMANY);
   }
2. Run Simbrain, create two neurons and connect them with a synapse. 
3. Double-click the synapse, look at the upper and lower bounds and increment then click okay.
4. Do this again.

You'll notice that they get multiplied by 10 each time because the "." is being parsed as a grouping separator, but the text field is being filled formatted such that "." is the decimal separator.

**Comment by jyoshimi** [comment]
Thanks for your work on this Zach.    I can try to push the change further through.   As I noted in the discussion of #34, I'd like to be able to see the problem on  my machine by changing localle.  Can you confirm you've been able to replicate the problem and if so post steps for replicating?

**Comment by zachtosi** [comment]
Just edited my post to include replication instructions!

**Comment by jyoshimi** [comment]
Fantastic thanks!

**Comment by fruddix** [comment]
I can verify this bug. A quick workaround for me was to run the Simbrain from console with US locale :
`java -jar -Duser.language=en -Duser.country=US -Duser.variant=US Simbrain.jar`

**Comment by jyoshimi** [comment]
Thanks for the tip fruddix. That should also be helpful in testing.

**Comment by jyoshimi** [comment]
Release 3.02 is now out so this is closed, the problem will linger for synapse dialogs.   For that I opened #37
