### ISSUE TITLE
I cant figure how to run the program.

### ISSUE THREAD

**Issue by Avallix** [simbrain/simbrain#38]
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/20584643/22191436/4df6bb78-e0f0-11e6-9ae9-b920fb0179eb.png">

When I double click Simbrain.jar nothing happens except a blip with the words simbrain on it. if I run the program through cmd as directed in the README.txt I get the error "could not find or load main class = jar". I already have java jdk..1.8.0_111.  Any ideas?

**Comment by jyoshimi** [comment]
Hi there,

Just to be sure everything is in place, can you show what's in that directory?  I think in dos it's  the "dir" command?

Also  to verify that "java" is using 1.8, can you run "java -version"   

So, attach a console showing what happens in that directory when you enter

> dir
> java -version
> java -jar Simbrain.jar

**Comment by Avallix** [comment]
![image](https://cloud.githubusercontent.com/assets/20584643/22318680/20673d00-e342-11e6-8939-d7fee30cc6fa.png)

I deleted and reinstalled the program. By double clicking simbrain.jar it did not work. However, using cmd and the commands you gave me it runs. 

Thank you.
