### ISSUE TITLE
RSVP Protocol and Data Graphing

### ISSUE THREAD

**Issue by edaggett17** [simbrain/simbrain#41]
Hello All,

This is not an issue with the program. I am simply hoping someone can point me in the right direction for some training tools regarding what I am attempting to do. I am sure that what I am attempting is simple and has a simple answer.

I have created a simple network in which I have "hardwired" the weights and parameters. In other words, I am not looking for this network to learn or change in any way. Instead, I want to run the network through iterations of the RSVP protocol, store the output data of selected neurons, and graph it. 

I have created the input tables for various combinations of trials within RSVP and have successfully run the network through each of them in a step wise (hitting the space key) manner. I would like to be able to tie these input tables together in a program that iterates the network through these tables, in a random fashion, for x amount of iterations, just as you would with a human subject. Then, I would like to compile the output data for selected neurons at each step of each iteration. I will then graph this data in MATLAB or similar platforms. 

Do any of you know of a training document that may show me how to create such a program/protocol? I have fairly limited programming knowledge (which is why Simbrain is so excellent). 

Thank you in advance for your help!

Cheers,

Eben

**Comment by jyoshimi** [comment]
Hi Eben,

This sounds very interesting.  Unfortunately, for something custom like this I do think you'll need to do some programming.   For the current Simbrain that would mean using Scripting.  We have limited docs here

http://www.simbrain.net/Documentation/docs/Pages/Scripting.html

In the next Simbrain it will be a bit easier, but still basically a kind of programming.  Best of luck!

Oh you can also discuss this stuff here: http://simbrain.963258.n4.nabble.com/


- Jef

**Comment by edaggett17** [comment]
Thank you, Jef!

This is exactly what I was hoping for. I will get started digging through the example scripts and will leverage the knowledge in the simbrain forum. 

Thank you!
